export const CREATE_BATCH = "CREATE_BATCH";
export const CREATE_BATCH_SUCCESS = "CREATE_BATCH_SUCCESS";
export const CREATE_BATCH_FAIL = "CREATE_BATCH_FAIL";

export const FETCH_TODAY_BATCH = "FETCH_TODAY_BATCH";