export const GET_GIFT_CARDS = "GET_GIFT_CARDS"
export const GET_GIFT_CARDS_SUCCESS = "GET_GIFT_CARDS_SUCCESS"
export const GET_GIFT_CARDS_FAIL = "GET_GIFT_CARDS_FAIL"

export const ADD_GIFT_CARD = "ADD_GIFT_CARD"
export const ADD_GIFT_CARD_SUCCESS = "ADD_GIFT_CARD_SUCCESS"
export const ADD_GIFT_CARD_FAIL = "ADD_GIFT_CARD_FAIL"


export const GET_GIFTCARDS_CATEGORIES = "GET_GIFTCARD_CATEGORIES"
export const GET_GIFTCARDS_CATEGORIES_SUCCESS = "GET_GIFTCARD_CATEGORIES_SUCCESS"
export const GET_GIFTCARDS_CATEGORIES_FAIL = "GET_GIFTCARD_CATEGORIES_FAIL"

export const UPDATE_GIFTCARD = "UPDATE_GIFTCARD"
export const UPDATE_GIFTCARD_SUCCESS = "UPDATE_GIFTCARD_SUCCESS"
export const UPDATE_GIFTCARD_FAIL = "UPDATE_GIFTCARD_FAIL"

export const DELETE_GIFTCARD = "DELETE_GIFTCARD"
export const DELETE_GIFTCARD_SUCCESS = "DELETE_GIFTCARD_SUCCESS"
export const DELETE_GIFTCARD_FAIL = "DELETE_GIFTCARD_FAIL"

export const UPDATE_GIFTCARD_CATEGORY = "UPDATE_GIFTCARD_CATEGORY"
export const UPDATE_GIFTCARD_CATEGORY_SUCCESS = "UPDATE_GIFTCARD_CATEGORY_SUCCESS"
export const UPDATE_GIFTCARD_CATEGORY_FAIL = "UPDATE_GIFTCARD_CATEGORY_FAIL"
